version: '3'

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
    - 8001:11434

  app:
    build:
      context: .
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    environment:
      - DATA_PATH=${DATA_PATH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]