version: '3'
services:
  app:
#    image: python:3.10
    build:
      context: .
#    ports:
#      - 8000:8000
    #volumes:
    #  - ./mount:/app
    command: tail -f /dev/null
    environment:
      - DATA_PATH=${DATA_PATH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]